package util

import "time"

const (
	Status               string        = "status"
	Hostname             string        = "hostname"
	Err                  string        = "err"
	CredentialProfile    string        = "credential_profile"
	Username             string        = "username"
	Password             string        = "password"
	SSHTimout            time.Duration = 30
	TCP                  string        = "tcp"
	DiscoveryProfile     string        = "discovery_profile"
	IP                   string        = "ip"
	Port                 string        = "port"
	Empty                string        = ""
	NewLine              string        = "\n"
	SpaceSeparator       string        = " "
	Discovered           string        = "Device discovered successfully!"
	Fail                 string        = "Fail"
	Colon                string        = ":"
	SystemProcess        string        = "system.process"
	ProcessPID           string        = "system.process.pid"
	ProcessCPU           string        = "system.process.cpu"
	ProcessMemory        string        = "system.process.memory"
	ProcessUser          string        = "system.process.user"
	ProcessCommand       string        = "system.process.command"
	InstalledMemory      string        = "system.memory.installed.bytes"
	UsedMemory           string        = "system.memory.used.bytes"
	UsedMemoryPercentage string        = "system.memory.used.percentage"
	FreeMemory           string        = "system.memory.free.bytes"
	FreeMemoryPercentage string        = "system.memory.free.percentage"
	AvailableMemory      string        = "system.memory.available.bytes"
	SwapMemory           string        = "system.memory.swap.bytes"
	OsVersion            string        = "system.os.version"
	SystemName           string        = "system.name"
	OsName               string        = "system.os.name"
	Uptime               string        = "system.uptime"
	Threads              string        = "system.threads"
	ContextSwitches      string        = "system.context.switches"
	RunningProcesses     string        = "system.running.processes"
	BlockProcesses       string        = "system.block.processes"
	SystemCPU            string        = "system.cpu"
	CPUCores             string        = "system.cpu.cores"
	CPUCore              string        = "system.cpu.core"
	CPUPercentage        string        = "system.cpu.percentage"
	CPUUserPercentage    string        = "system.cpu.user.percentage"
	CPUIdlePercentage    string        = "system.cpu.idle.percentage"
)
